(function(g){var window=this;var oDa=function(a,b){return g.bc(a,b)},a6=function(a){g.jn(a,"zx",g.Bb());
return a},b6=function(a,b,c){g.Ba(c)||(c=[String(c)]);
g.mn(a.o,b,c)},pDa=function(a,b){var c=[];
g.Uk(b,function(a){try{var b=g.KD.prototype.A.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.u(b)?g.JD(b)&&c.push(a):c.push(a)},a);
return c},qDa=function(a,b){var c=pDa(a,b);
(0,g.D)(c,function(a){g.KD.prototype.remove.call(this,a)},a)},rDa=function(a){if(a.Qd){if(a.Qd.locationOverrideToken)return{locationOverrideToken:a.Qd.locationOverrideToken};
if(null!=a.Qd.latitudeE7&&null!=a.Qd.longitudeE7)return{latitudeE7:a.Qd.latitudeE7,longitudeE7:a.Qd.longitudeE7}}return null},sDa=function(a,b,c,d){var e=new g.$m(null,void 0);
a&&g.an(e,a);b&&g.bn(e,b);c&&g.cn(e,c);d&&g.dn(e,d);return e},tDa=function(a){return a?a.dataset?a.dataset[g.AF("loaded")]:a.getAttribute("data-loaded"):null},c6=function(a,b){g.tG[a]=!0;
var c=g.rG();c&&c.publish.apply(c,arguments);g.tG[a]=!1},uDa=function(a){g.uG[a]&&(a=g.uG[a],(0,g.D)(a,function(a){g.sG[a]&&delete g.sG[a]}),a.length=0)},vDa=function(a){var b=g.rG();
if(b)if(b.clear(a),a)uDa(a);else for(var c in g.uG)uDa(c)},d6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.B=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.Um;this.o=this.A="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",wDa(this,a.capabilities||""),xDa(this,a.experiments||""),this.A=a.remoteControllerUrl||"",
this.o=a.localChannelEncryptionKey||"")},wDa=function(a,b){a.capabilities.clear();
(0,g.de)(b.split(","),g.Ha(oDa,yDa)).forEach(function(b){a.capabilities.add(b)})},xDa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},e6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},f6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},zDa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},ADa=function(a){return new e6(a)},BDa=function(a){return g.Ba(a)?(0,g.J)(a,ADa):[]},g6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},h6=function(a){return g.Ba(a)?"["+(0,g.J)(a,g6).join(",")+"]":"null"},i6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},CDa=function(a){return(0,g.J)(a,function(a){return{key:a.id,
name:a.name}})},j6=function(a,b){return g.Oa(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},k6=function(a,b){return g.Oa(a,function(a){return f6(a,b)})},DDa=function(){var a=(0,g.CH)();
a&&qDa(a,a.o.ge(!0))},l6=function(){var a=g.FH("yt-remote-connected-devices")||[];
g.nb(a);return a},EDa=function(a){if(g.Ua(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.J)(a,function(a,b){return 0==b?a:a.substring(c.length)})},FDa=function(a){g.EH("yt-remote-connected-devices",a,86400)},n6=function(){if(m6)return m6;
var a=g.FH("yt-remote-device-id");a||(a=i6(),g.EH("yt-remote-device-id",a,31536E3));for(var b=l6(),c=1,d=a;g.Ta(b,d);)c++,d=a+"#"+c;return m6=d},o6=function(){var a=l6(),b=n6();
g.Ta(a,b);g.HH()&&g.pb(a,b);a=EDa(a);if(g.Ua(a))try{g.aH("remote_sid")}catch(c){}else try{g.$G("remote_sid",a.join(","),-1)}catch(c){}},GDa=function(){return g.FH("yt-remote-session-browser-channel")},HDa=function(){return g.FH("yt-remote-local-screens")||[]},IDa=function(){g.EH("yt-remote-lounge-token-expiration",!0,86400)},JDa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.J)(HDa(),function(a){return a.loungeToken}),c=(0,g.J)(a,function(a){return a.loungeToken});
(0,g.Im)(c,function(a){return!g.Ta(b,a)})&&IDa();
g.EH("yt-remote-local-screens",a,31536E3)},KDa=function(a,b){g.EH("yt-remote-session-browser-channel",a);
g.EH("yt-remote-session-screen-id",b);var c=l6(),d=n6();g.Ta(c,d)||c.push(d);FDa(c);o6()},p6=function(a){a||(g.GH("yt-remote-session-screen-id"),g.GH("yt-remote-session-video-id"));
o6();a=l6();g.Ya(a,n6());FDa(a)},LDa=function(){if(!q6){var a=g.VD();
a&&(q6=new g.ED(a))}return q6?!!q6.get("yt-remote-use-staging-server"):!1},MDa=function(){var a=window.document.createElement("a");
g.rd(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Fb(a)},NDa=function(a,b,c){c=void 0===c?null:c;
var d=g.Xd("SCRIPT");d.id=a;d.onload=function(){b&&(0,window.setTimeout)(b,0)};
d.onreadystatechange=function(){switch(d.readyState){case "loaded":case "complete":d.onload()}};
c&&d.setAttribute("nonce",c);g.td(d,g.te("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));a=window.document.getElementsByTagName("head")[0]||window.document.body;a.insertBefore(d,a.firstChild);return d},ODa=function(a){a=void 0===a?null:a;
var b=MDa(),c=window.document.getElementById(b),d=c&&tDa(c);d||c&&!d||(c=NDa(b,function(){tDa(c)||(g.BF(c,"loaded","true"),g.yG(b),g.AE(g.Ha(vDa,b),0))},a))},PDa=function(){var a=void 0===a?null:a;
window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):ODa(a)},r6=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},QDa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},s6=function(a){a.length?RDa(a.shift(),function(){s6(a)}):t6()},SDa=function(a){return"chrome-extension://"+a+u6},RDa=function(a,
b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},v6=function(a){return 0<=window.navigator.userAgent.indexOf(a)},t6=function(){var a=QDa();
a&&a(!1,"No cast extension found")},w6=function(){if(TDa){var a=2,b=QDa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;RDa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",t6,c)}},UDa=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(w6(),a({command:"cast.sender.init"}))},VDa=function(){w6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);s6(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+u6,"//www.gstatic.com/eureka/clank"+u6])},x6=function(a,b,c){g.K.call(this);
this.F=null!=c?(0,g.B)(a,c):a;this.Hd=b;this.D=(0,g.B)(this.RK,this);this.o=!1;this.A=0;this.B=this.Ha=null;this.C=[]},y6=function(){},z6=function(a,b,c,d){this.o=a;
this.B=b;this.G=c;this.F=d||1;this.C=45E3;this.Y=new g.qn(this);this.A=new g.Hg;this.A.setInterval(250)},XDa=function(a,b,c){a.Xj=1;
a.Ah=a6(b.clone());a.nj=c;a.D=!0;WDa(a,null)},A6=function(a,b,c,d,e){a.Xj=1;
a.Ah=a6(b.clone());a.nj=null;a.D=c;e&&(a.uF=!1);WDa(a,d)},WDa=function(a,b){a.Tk=(0,g.I)();
B6(a);a.ci=a.Ah.clone();b6(a.ci,"t",a.F);a.Nn=0;a.Wc=a.o.Qs(a.o.Fn()?b:null);0<a.Lt&&(a.Jq=new g.Bl((0,g.B)(a.KG,a,a.Wc),a.Lt));a.Y.W(a.Wc,"readystatechange",a.fW);var c=a.Mi?g.kc(a.Mi):{};a.nj?(a.zr="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Wc.send(a.ci,a.zr,a.nj,c)):(a.zr="GET",a.uF&&!g.Sd&&(c.Connection="close"),a.Wc.send(a.ci,a.zr,null,c));a.o.Hf(1)},$Da=function(a,b,c){for(var d=!0;!a.xi&&a.Nn<c.length;){var e=YDa(a,c);
if(e==C6){4==b&&(a.Bh=4,D6(15),d=!1);break}else if(e==ZDa){a.Bh=4;D6(16);d=!1;break}else E6(a,e)}4==b&&0==c.length&&(a.Bh=1,D6(17),d=!1);a.Of=a.Of&&d;d||(F6(a),G6(a))},YDa=function(a,b){var c=a.Nn,d=b.indexOf("\n",c);
if(-1==d)return C6;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return ZDa;d+=1;if(d+c>b.length)return C6;var e=b.substr(d,c);a.Nn=d+c;return e},bEa=function(a,b){a.Tk=(0,g.I)();
B6(a);var c=b?window.location.hostname:"";a.ci=a.Ah.clone();g.jn(a.ci,"DOMAIN",c);g.jn(a.ci,"t",a.F);try{a.Pf=new window.ActiveXObject("htmlfile")}catch(n){F6(a);a.Bh=7;D6(22);G6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in H6)k=H6[l];else if(l in aEa)k=H6[l]=aEa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=H6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.vd(g.Jc("b/12014412"),d+"</body></html>");a.Pf.open();a.Pf.write(g.kd(c));a.Pf.close();a.Pf.parentWindow.m=(0,g.B)(a.oV,a);a.Pf.parentWindow.d=(0,g.B)(a.BE,a,!0);a.Pf.parentWindow.rpcClose=(0,g.B)(a.BE,a,!1);c=a.Pf.createElement("DIV");a.Pf.parentWindow.document.body.appendChild(c);d=g.Xc(a.ci.toString());d=g.vb(g.Uc(d));d=g.vd(g.Jc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.qd(c,g.kd(d));a.o.Hf(1)},
B6=function(a){a.Fx=(0,g.I)()+a.C;
cEa(a,a.C)},cEa=function(a,b){if(null!=a.ql)throw Error("WatchDog timer not null");
a.ql=I6((0,g.B)(a.EV,a),b)},J6=function(a){a.ql&&(g.x.clearTimeout(a.ql),a.ql=null)},G6=function(a){a.o.SA()||a.xi||a.o.wq(a)},F6=function(a){J6(a);
g.tf(a.Jq);a.Jq=null;a.A.stop();g.wn(a.Y);if(a.Wc){var b=a.Wc;a.Wc=null;b.abort();b.dispose()}a.Pf&&(a.Pf=null)},E6=function(a,b){try{a.o.tE(a,b),a.o.Hf(4)}catch(c){}},eEa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;dEa(a,b,function(e){e?c(!0):g.x.setTimeout(function(){eEa(a,b,c,d,f)},f)})}},dEa=function(a,b,c){var d=new window.Image;
d.onload=function(){try{K6(d),c(!0)}catch(e){}};
d.onerror=function(){try{K6(d),c(!1)}catch(e){}};
d.onabort=function(){try{K6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{K6(d),c(!1)}catch(e){}};
g.x.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},K6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},fEa=function(a){this.o=a;
this.A=new y6},gEa=function(a){var b=L6(a.o,a.wl,"/mail/images/cleardot.gif");
a6(b);eEa(b.toString(),5E3,(0,g.B)(a.WJ,a),3,2E3);a.Hf(1)},N6=function(a){var b=a.o.J;
if(null!=b)D6(5),b?(D6(11),M6(a.o,a,!1)):(D6(12),M6(a.o,a,!0));else if(a.Je=new z6(a,void 0,void 0,void 0),a.Je.Mi=a.Jt,b=a.o,b=L6(b,b.Fn()?a.jm:null,a.Kt),D6(5),!g.Qd||g.Bc(10))b6(b,"TYPE","xmlhttp"),A6(a.Je,b,!1,a.jm,!1);else{b6(b,"TYPE","html");var c=a.Je;a=!!a.jm;c.Xj=3;c.Ah=a6(b.clone());bEa(c,a)}},O6=function(a,b,c){this.o=1;
this.A=[];this.C=[];this.D=new y6;this.H=a||null;this.J=null!=b?b:null;this.F=c||!1},hEa=function(a,b){this.o=a;
this.map=b;this.context=null},iEa=function(a){g.vf.call(this,"statevent",a)},jEa=function(a,b){g.vf.call(this,"timingevent",a);
this.size=b},kEa=function(a){g.vf.call(this,"serverreachability",a)},nEa=function(a){lEa(a);
if(3==a.o){var b=a.kn++,c=a.ep.clone();g.jn(c,"SID",a.B);g.jn(c,"RID",b);g.jn(c,"TYPE","terminate");P6(a,c);b=new z6(a,a.B,b,void 0);b.Xj=2;b.Ah=a6(c.clone());(new window.Image).src=b.Ah;b.Tk=(0,g.I)();B6(b)}mEa(a)},oEa=function(a){a.rK(1,0);
a.ep=L6(a,null,a.It);Q6(a)},lEa=function(a){a.oh&&(a.oh.abort(),a.oh=null);
a.Bc&&(a.Bc.cancel(),a.Bc=null);a.Bg&&(g.x.clearTimeout(a.Bg),a.Bg=null);R6(a);a.ne&&(a.ne.cancel(),a.ne=null);a.uh&&(g.x.clearTimeout(a.uh),a.uh=null)},pEa=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.A.push(new hEa(a.gR++,b));2!=a.o&&3!=a.o||Q6(a)},Q6=function(a){a.ne||a.uh||(a.uh=I6((0,g.B)(a.zE,a),0),a.Oj=0)},rEa=function(a,b){if(1==a.o){if(!b){a.kn=Math.floor(1E5*Math.random());
var c=a.kn++,d=new z6(a,"",c,void 0);d.Mi=null;var e=S6(a),f=a.ep.clone();g.jn(f,"RID",c);g.jn(f,"CVER","1");P6(a,f);XDa(d,f,e);a.ne=d;a.o=2}}else 3==a.o&&(b?qEa(a,b):0==a.A.length||a.ne||qEa(a))},qEa=function(a,b){if(b)if(6<a.zi){a.A=a.C.concat(a.A);
a.C.length=0;var c=a.kn-1;var d=S6(a)}else c=b.G,d=b.nj;else c=a.kn++,d=S6(a);var e=a.ep.clone();g.jn(e,"SID",a.B);g.jn(e,"RID",c);g.jn(e,"AID",a.rk);P6(a,e);c=new z6(a,a.B,c,a.Oj+1);c.Mi=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.ne=c;XDa(c,e,d)},P6=function(a,b){if(a.Gd){var c=a.Gd.AA();
c&&g.Ob(c,function(a,c){g.jn(b,c,a)})}},S6=function(a){var b=Math.min(a.A.length,1E3),c=["count="+b];
if(6<a.zi&&0<b){var d=a.A[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.A[e].o,k=a.A[e].map;f=6>=a.zi?e:f-d;try{g.Ob(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.C=a.C.concat(a.A.splice(0,b));
return c.join("&")},sEa=function(a){a.Bc||a.Bg||(a.G=1,a.Bg=I6((0,g.B)(a.yE,a),0),a.Fj=0)},T6=function(a){if(a.Bc||a.Bg||3<=a.Fj)return!1;
a.G++;a.Bg=I6((0,g.B)(a.yE,a),tEa(a,a.Fj));a.Fj++;return!0},M6=function(a,b,c){a.xr=c;
a.Zf=b.Ng;a.F||oEa(a)},R6=function(a){null!=a.Bi&&(g.x.clearTimeout(a.Bi),a.Bi=null)},tEa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},U6=function(a,b){if(2==b||9==b){var c=null;
a.Gd&&(c=null);var d=(0,g.B)(a.VW,a);c||(c=new g.$m("//www.google.com/images/cleardot.gif"),a6(c));dEa(c.toString(),1E4,d)}else D6(2);uEa(a,b)},uEa=function(a,b){a.o=0;
a.Gd&&a.Gd.Az(b);mEa(a);lEa(a)},mEa=function(a){a.o=0;
a.Zf=-1;if(a.Gd)if(0==a.C.length&&0==a.A.length)a.Gd.Ds();else{g.bb(a.C);var b=g.bb(a.A);a.C.length=0;a.A.length=0;a.Gd.Ds(b)}},L6=function(a,b,c){var d=g.kn(c);
if(""!=d.A)b&&g.bn(d,b+"."+d.A),g.cn(d,d.D);else{var e=window.location;d=sDa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Ml&&g.Ob(a.Ml,function(a,b){g.jn(d,b,a)});
g.jn(d,"VER",a.zi);P6(a,d);return d},I6=function(a,b){if(!g.Da(a))throw Error("Fn must not be null and must be a function");
return g.x.setTimeout(function(){a()},b)},D6=function(a){V6.dispatchEvent(new iEa(V6,a))},vEa=function(){},wEa=function(a,b){this.action=a;
this.params=b||{}},W6=function(a,b){g.K.call(this);
this.o=new g.V(this.fV,0,this);g.M(this,this.o);this.Hd=5E3;this.A=0;if(g.Da(a))b&&(a=(0,g.B)(a,b));else if(a&&g.Da(a.handleEvent))a=(0,g.B)(a.handleEvent,a);else throw Error("Invalid listener argument");this.B=a},X6=function(a,b,c){this.L=a;
this.F=b;this.B=new g.DD;this.A=new W6(this.yX,this);this.o=this.kb=null;this.K=!1;this.D=null;this.J="";this.H=this.C=0;this.G=[];this.M=c||!1},xEa=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.xr,sessionId:a.o.B,arrayId:a.o.rk}},yEa=function(a,b){a.H=b||0;
a.A.stop();a.o&&(3==a.o.o&&rEa(a.o),nEa(a.o));a.H=0},Y6=function(a){return!!a.o&&3==a.o.o},zEa=function(a,b){(a.F.loungeIdToken=b)||a.A.stop()},Z6=function(a){this.port=this.domain="";
this.o="/api/lounge";this.A=!0;a=a||window.document.location.href;var b=g.Wg(a)||"";b&&(this.port=":"+b);this.domain=g.Vg(a)||"";a=g.Mb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Eb(a,"10.0")&&(this.A=!1))},$6=function(a,b){var c=a.o;
if(g.u(void 0)?0:a.A)c="https://"+a.domain+a.port+a.o;return g.eh(c+b,{})},a7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ha(a.C,d,!0),onError:g.Ha(a.B,e),Md:g.Ha(a.D,e)};c&&(a.Tb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.RE(b,a)},DEa=function(){var a=AEa;
BEa();b7.push(a);CEa(b7)},c7=function(a,b){BEa();
var c=b7,d=EEa(a,String(b));g.Ua(c)?FEa(d):(CEa(c),(0,g.D)(c,function(a){a(d)}))},BEa=function(){b7||(b7=g.y("yt.mdx.remote.debug.handlers_")||[],g.ya("yt.mdx.remote.debug.handlers_",b7,void 0))},FEa=function(a){var b=(d7+1)%50;
d7=b;e7[b]=a;f7||(f7=49==b)},CEa=function(a){var b=e7;
if(b[0]){var c=d7,d=f7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.D)(a,function(a){a(e)})}while(d!=c);
e7=Array(50);d7=-1;f7=!1}},EEa=function(a,b){var c=((0,g.I)()-GEa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},g7=function(a){g.iG.call(this);
this.G=a;this.o=[]},HEa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.o.push(b);return!0},IEa=function(a,b){var c=a.o.length!=b.length;
a.o=(0,g.de)(a.o,function(a){return!!j6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=HEa(a,b[d])||c;return c},JEa=function(a,b){var c=a.o.length;
a.o=(0,g.de)(a.o,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.o.length<c},h7=function(a,b,c,d){g.iG.call(this);
this.F=a;this.D=b;this.B=c;this.C=d;this.A=0;this.o=null;this.Ha=window.NaN},j7=function(a){g7.call(this,"LocalScreenService");
this.B=a;this.A=window.NaN;i7(this);this.info("Initializing with "+h6(this.o))},KEa=function(a){if(a.o.length){var b=(0,g.J)(a.o,function(a){return a.id}),c=$6(a.B,"/pairing/get_lounge_token_batch");
a7(a.B,c,{screen_ids:b.join(",")},(0,g.B)(a.gL,a),(0,g.B)(a.fL,a))}},i7=function(a){var b=BDa(HDa());
b=(0,g.de)(b,function(a){return!a.uuid});
return IEa(a,b)},k7=function(a,b){JDa((0,g.J)(a.o,zDa));
b&&IDa()},m7=function(a,b){g.iG.call(this);
this.F=b;var c=g.FH("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.F(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Ta(c,l)}this.o=d;this.D=a;this.B=this.C=window.NaN;this.A=null;l7("Initialized with "+g.Ng(this.o))},LEa=function(a,b,c){var d=$6(a.D,"/pairing/get_screen_availability");
a7(a.D,d,{lounge_token:b.token},(0,g.B)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.B)(function(){c(!1)},a))},n7=function(a,b){a:if(g.Tb(b)!=g.Tb(a.o))var c=!1;
else{c=g.Zb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(l7("Updated online screens: "+g.Ng(a.o)),a.o=b,a.U("screenChange"));MEa(a)},o7=function(a){(0,window.isNaN)(a.B)||g.CE(a.B);
a.B=g.AE((0,g.B)(a.Dw,a),0<a.C&&a.C<(0,g.I)()?2E4:1E4)},l7=function(a){c7("OnlineScreenService",a)},NEa=function(a){var b={};
(0,g.D)(a.F(),function(a){a.token?b[a.token]=a.id:this.uc("Requesting availability of screen w/o lounge token.")});
return b},MEa=function(a){a=g.Zb(g.Pb(a.o,function(a){return a}));
g.nb(a);a.length?g.EH("yt-remote-online-screen-ids",a.join(","),60):g.GH("yt-remote-online-screen-ids")},p7=function(a){g7.call(this,"ScreenService");
this.F=a;this.A=this.B=null;this.C=[];this.D={};OEa(this)},QEa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var k=a.De();if(k=(c?k6(k,c):null)||k6(k,b)){k.uuid=b;var l=q7(a,k);LEa(a.A,l,function(a){e(a?l:null)})}else c?PEa(a,c,(0,g.B)(function(a){var f=q7(this,new e6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));LEa(this.A,f,function(a){e(a?f:null)})},a),f):e(null)},REa=function(a,b){for(var c=0,d=a.o.length;c<d;++c)if(a.o[c].name==b)return a.o[c];
return null},PEa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Tb:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.RE($6(a.F,"/pairing/get_lounge_token_batch"),e)},SEa=function(a){a.o=a.B.De();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.o.length;b<d;++b){var e=a.o[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+h6(a.o))},OEa=function(a){r7(a);
a.B=new j7(a.F);a.B.subscribe("screenChange",(0,g.B)(a.tL,a));SEa(a);a.C=BDa(g.FH("yt-remote-automatic-screen-cache")||[]);r7(a);a.info("Initializing automatic screens: "+h6(a.C));a.A=new m7(a.F,(0,g.B)(a.De,a,!0));a.A.subscribe("screenChange",(0,g.B)(function(){this.U("onlineScreenChange")},a))},q7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=k6(a.C,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.C.push(b),g.EH("yt-remote-automatic-screen-cache",(0,g.J)(a.C,zDa)));r7(a);a.D[b.uuid]=b.id;g.EH("yt-remote-device-id-map",a.D,31536E3);return b},r7=function(a){a.D=g.FH("yt-remote-device-id-map")||{}},s7=function(a,b,c){g.iG.call(this);
this.M=c;this.J=a;this.A=b;this.B=null},t7=function(a,b){c7(a.M,b)},u7=function(a,b){s7.call(this,a,b,"CastSession");
this.o=null;this.C=0;this.F=(0,g.B)(this.EX,this);this.D=(0,g.B)(this.QV,this);this.C=g.AE((0,g.B)(function(){TEa(this,null)},this),12E4)},UEa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Ng(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.A,(0,g.B)(function(){t7(this,"Failed to send message: getMdxSessionStatus.")},a)):t7(a,"Sending yt message without session: "+g.Ng(b))},TEa=function(a,b){g.CE(a.C);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.B||a.B.id!=b){var c=(0,g.B)(a.xq,a),d=(0,g.B)(a.Ie,a);a.IA(b,c,d,5)}}else a.Ie(Error("Waiting for session status timed out."))},v7=function(a,b,c){s7.call(this,a,b,"DialSession");
this.C=this.H=null;this.K="";this.O=c;this.D=null;this.G=g.A;this.F=window.NaN;this.L=(0,g.B)(this.HX,this);this.o=g.A},VEa=function(a){a.o=a.J.TG(a.K,a.A.label,a.A.friendlyName,(0,g.B)(function(a){this.o=g.A;
this.xq(a)},a),(0,g.B)(function(a){this.o=g.A;
this.Ie(a)},a))},WEa=function(a){var b={};
b.pairingCode=a.K;b.theme=a.O;if(a.D){var c=a.D.currentTime||0;b.v=a.D.videoId;b.t=c}LDa()&&(b.env_useStageMdx=1);return g.ch(b)},w7=function(a,b){s7.call(this,a,b,"ManualSession");
this.o=g.AE((0,g.B)(this.tk,this,null),150)},x7=function(a,b,c,d){g.iG.call(this);
this.A=a;this.G=b||"233637DE";this.F=c||"cl";this.H=d||!1;this.o=null;this.D=!1;this.B=[];this.C=(0,g.B)(this.tU,this)},XEa=function(a,b){return b?g.Oa(a.B,function(a){return f6(b,a.label)},a):null},y7=function(a){c7("Controller",a)},AEa=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},z7=function(a){return a.D||!!a.B.length||!!a.o},A7=function(a,b,c){b!=a.o&&(g.tf(a.o),(a.o=b)?(c?a.U("yt-remote-cast2-receiver-resumed",b.A):a.U("yt-remote-cast2-receiver-selected",
b.A),b.subscribe("sessionScreen",(0,g.B)(a.wE,a,b)),b.B?a.U("yt-remote-cast2-session-change",b.B):c&&a.o.tk(null)):a.U("yt-remote-cast2-session-change",null))},YEa=function(a){var b=a.A.SG(),c=a.o&&a.o.A;
a=(0,g.J)(b,function(a){c&&f6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=XEa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},dFa=function(a,b,c,d,e,f,k){ZEa()?$Ea(b,e,f,k)&&(C7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?aFa(a,c):(window.__onGCastApiAvailable=function(b,d){b?aFa(a,c):(D7("Failed to load cast API: "+d),E7(!1),C7(!1),g.GH("yt-remote-cast-available"),g.GH("yt-remote-cast-receiver"),bFa(),
c(!1))},d?PDa():v6("CriOS")?UDa():v6("Android")&&v6("Chrome/")&&window.navigator.presentation?VDa():window.chrome&&window.navigator.presentation&&!v6("Edge")?(w6(),s6(cFa.map(SDa))):t6())):B7("Cannot initialize because not running Chrome")},bFa=function(){B7("dispose");
var a=F7();a&&a.dispose();g.ya("yt.mdx.remote.cloudview.instance_",null,void 0);eFa(!1);g.wG(G7);G7.length=0},H7=function(){return!!g.FH("yt-remote-cast-installed")},fFa=function(){var a=g.FH("yt-remote-cast-receiver");
return a?a.friendlyName:null},gFa=function(){B7("clearCurrentReceiver");
g.GH("yt-remote-cast-receiver")},hFa=function(){return H7()?F7()?F7().getCastSession():(D7("getCastSelector: Cast is not initialized."),null):(D7("getCastSelector: Cast API is not installed!"),null)},J7=function(){H7()?F7()?I7()?(B7("Requesting cast selector."),F7().requestSession()):(B7("Wait for cast API to be ready to request the session."),G7.push(g.vG("yt-remote-cast2-api-ready",J7))):D7("requestCastSelector: Cast is not initialized."):D7("requestCastSelector: Cast API is not installed!")},K7=
function(a,b){I7()?F7().setConnectedScreenStatus(a,b):D7("setConnectedScreenStatus called before ready.")},ZEa=function(){var a=0<=g.Mb.search(/ (CrMo|Chrome|CriOS)\//);
return g.QI||a},iFa=function(a,b){F7().init(a,b)},$Ea=function(a,b,c,d){var e=!1;
F7()||(a=new x7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.EH("yt-remote-cast-available",a);c6("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){B7("onReceiverSelected: "+a.friendlyName);
g.EH("yt-remote-cast-receiver",a);c6("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){B7("onReceiverResumed: "+a.friendlyName);
g.EH("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){B7("onSessionChange: "+g6(a));
a||g.GH("yt-remote-cast-receiver");c6("yt-remote-cast2-session-change",a)}),g.ya("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
B7("cloudview.createSingleton_: "+e);return e},F7=function(){return g.y("yt.mdx.remote.cloudview.instance_")},aFa=function(a,b){E7(!0);
C7(!1);iFa(a,function(a){a?(eFa(!0),g.yG("yt-remote-cast2-api-ready")):(D7("Failed to initialize cast API."),E7(!1),g.GH("yt-remote-cast-available"),g.GH("yt-remote-cast-receiver"),bFa());b(a)})},B7=function(a){c7("cloudview",a)},D7=function(a){c7("cloudview",a)},E7=function(a){B7("setCastInstalled_ "+a);
g.EH("yt-remote-cast-installed",a)},I7=function(){return!!g.y("yt.mdx.remote.cloudview.apiReady_")},eFa=function(a){B7("setApiReady_ "+a);
g.ya("yt.mdx.remote.cloudview.apiReady_",a,void 0)},C7=function(a){g.ya("yt.mdx.remote.cloudview.initializing_",a,void 0)},L7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.F=this.G=0;this.o=null;this.hasNext=this.eg=!1;this.J=this.H=this.A=this.C=0;this.B=window.NaN;this.D=!1;this.reset(a)},M7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.eg=!1;a.hasNext=!1;a.G=0;a.F=(0,g.I)();a.C=0;a.A=0;a.H=0;a.J=0;a.B=window.NaN;a.D=!1},N7=function(a){return a.tb()?((0,g.I)()-a.F)/1E3:0},O7=function(a,b){a.G=b;
a.F=(0,g.I)()},P7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.I)()-a.F)/1E3+a.G;
case -1E3:return 0}return a.G},Q7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&M7(a)},R7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.lc(a.o);b.hasPrevious=a.eg;b.hasNext=a.hasNext;b.playerTime=a.G;b.playerTimeAt=a.F;b.seekableStart=a.C;b.seekableEnd=a.A;b.duration=a.H;b.loadedTime=a.J;b.liveIngestionTime=a.B;return b},T7=function(a,b){g.iG.call(this);
this.o=0;this.C=a;this.F=[];this.D=new g.UC;this.B=this.A=null;this.J=(0,g.B)(this.PR,this);this.G=(0,g.B)(this.nn,this);this.H=(0,g.B)(this.OR,this);this.K=(0,g.B)(this.bS,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Nx,this),jFa(this))):c=3;0!=c&&(b?this.Nx(c):g.AE((0,g.B)(function(){this.Nx(c)},this),0));
var d=hFa();d&&S7(this,d);this.subscribe("yt-remote-cast2-session-change",this.K)},U7=function(a){return new L7(a.C.getPlayerContextData())},jFa=function(a){(0,g.D)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.F.push(this.C.subscribe(a,g.Ha(this.oU,a),this))},a)},kFa=function(a){(0,g.D)(a.F,function(a){this.C.unsubscribeByKey(a)},a);
a.F.length=0},V7=function(a,b){50>a.D.Lc()&&g.WC(a.D,b)},X7=function(a,b,c){var d=U7(a);
O7(d,c);-1E3!=d.playerState&&(d.playerState=b);W7(a,d)},Y7=function(a,b,c){a.C.sendMessage(b,c)},W7=function(a,b){kFa(a);
a.C.setPlayerContextData(R7(b));jFa(a)},S7=function(a,b){a.B&&(a.B.removeUpdateListener(a.J),a.B.removeMediaListener(a.G),a.nn(null));
a.B=b;a.B&&(c7("CP","Setting cast session: "+a.B.sessionId),a.B.addUpdateListener(a.J),a.B.addMediaListener(a.G),a.B.media.length&&a.nn(a.B.media[0]))},lFa=function(a){var b=a.A.media,c=a.A.customData;
if(b&&c){var d=U7(a);b.contentId!=d.videoId&&c7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;O7(d,a.A.getEstimatedTime());W7(a,d)}else c7("CP","No cast media video. Ignoring state update.")},Z7=function(a,b,c){return(0,g.B)(function(a){this.uc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.uc("Retrying "+b+" using MDx browser channel."),Y7(this,b,c))},a)},$7=function(a,b,c){g.iG.call(this);
this.D=window.NaN;this.O=!1;this.K=this.J=this.L=this.M=window.NaN;this.V=[];this.C=this.G=this.B=this.qb=this.o=null;this.ua=a;this.V.push(g.SF(window,"beforeunload",(0,g.B)(this.VK,this)));this.A=[];this.qb=new L7;this.ba=b.id;this.o=mFa(this,c);this.o.subscribe("handlerOpened",this.TR,this);this.o.subscribe("handlerClosed",this.QR,this);this.o.subscribe("handlerError",this.RR,this);this.o.subscribe("handlerMessage",this.SR,this);zEa(this.o,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.qb.videoId;g.HH()&&g.EH("yt-remote-session-video-id",a)},this)},a8=function(a){c7("conn",a)},mFa=function(a,b){return new X6($6(a.ua,"/bc"),b)},b8=function(a,b){a.U("proxyStateChange",b)},nFa=function(a){a.D=g.AE((0,g.B)(function(){a8("Connecting timeout");
this.F(1)},a),2E4)},c8=function(a){g.CE(a.D);
a.D=window.NaN},d8=function(a){g.CE(a.M);
a.M=window.NaN},oFa=function(a){e8(a);
a.L=g.AE((0,g.B)(function(){f8(this,"getNowPlaying")},a),2E4)},e8=function(a){g.CE(a.L);
a.L=window.NaN},qFa=function(a,b){b&&(c8(a),d8(a));
b==(Y6(a.o)&&(0,window.isNaN)(a.D))?b&&(b8(a,1),f8(a,"getSubtitlesTrack")):b?(a.Z()&&a.qb.reset(),b8(a,1),f8(a,"getNowPlaying"),pFa(a)):a.F(1)},rFa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.qb.videoId&&(g.ec(b.params)?a.qb.o=null:a.qb.o=b.params,a.U("remotePlayerChange"))},sFa=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.qb.listId=b.params.listId||a.qb.listId;Q7(a.qb,c,d);a.U("remoteQueueChange")},uFa=function(a,b){b.params=b.params||{};
sFa(a,b);tFa(a,b);a.U("autoplayDismissed")},tFa=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
O7(a.qb,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.qb.playerState&&(c=-1E3);a.qb.playerState=c;c=Number(b.params.loadedTime);a.qb.J=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.qb.H=(0,window.isNaN)(c)?0:c;c=a.qb;var d=Number(b.params.liveIngestionTime);c.B=d;c.D=(0,window.isNaN)(d)?!1:!0;c=a.qb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.C=(0,window.isNaN)(d)?0:d;c.A=(0,window.isNaN)(e)?0:
e;1==a.qb.playerState?oFa(a):e8(a);a.U("remotePlayerChange")},vFa=function(a,b){if(-1E3!=a.qb.playerState){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.qb.playerState=c;c=(0,window.parseInt)(b.params.currentTime,10);O7(a.qb,(0,window.isNaN)(c)?0:c);a.U("remotePlayerChange")}},wFa=function(a,b){var c="true"==b.params.muted;
a.qb.volume=(0,window.parseInt)(b.params.volume,10);a.qb.muted=c;a.U("remotePlayerChange")},xFa=function(a,b){a.G=b.params.videoId;
a.U("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},yFa=function(a,b){var c="true"==b.params.hasNext;
a.qb.eg="true"==b.params.hasPrevious;a.qb.hasNext=c;a.U("previousNextChange")},pFa=function(a){g.CE(a.K);
a.K=g.AE((0,g.B)(a.F,a,1),864E5)},f8=function(a,b,c){c?a8("Sending: action="+b+", params="+g.Ng(c)):a8("Sending: action="+b);
a.o.sendMessage(b,c)},g8=function(a){g7.call(this,"ScreenServiceProxy");
this.pd=a;this.A=[];this.A.push(this.pd.$_s("screenChange",(0,g.B)(this.CX,this)));this.A.push(this.pd.$_s("onlineScreenChange",(0,g.B)(this.KT,this)))},DFa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.pE("MDX_CONFIG")||b;DDa();o6();h8||(h8=new Z6(b?b.loungeApiHost:void 0),LDa()&&(h8.o="/api/loungedev"));i8||(i8=g.y("yt.mdx.remote.deferredProxies_")||[],g.ya("yt.mdx.remote.deferredProxies_",i8,void 0));zFa();var c=j8();if(!c){var d=new p7(h8);g.ya("yt.mdx.remote.screenService_",d,void 0);c=j8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);dFa(a,d,function(a){a?k8()&&K7(k8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){c6("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.y("yt.mdx.remote.initialized_")&&(g.ya("yt.mdx.remote.initialized_",!0,void 0),l8("Initializing: "+g.Ng(b)),m8.push(g.vG("yt-remote-cast2-availability-change",function(){c6("yt-remote-receiver-availability-change")})),m8.push(g.vG("yt-remote-cast2-receiver-selected",function(){n8(null);
c6("yt-remote-auto-connect","cast-selector-receiver")})),m8.push(g.vG("yt-remote-cast2-receiver-resumed",function(){c6("yt-remote-receiver-resumed","cast-selector-receiver")})),m8.push(g.vG("yt-remote-cast2-session-change",AFa)),m8.push(g.vG("yt-remote-connection-change",function(a){a?K7(k8(),"YouTube TV"):o8()||(K7(null,null),gFa())})),a=p8(),b.isAuto&&(a.id+="#dial"),g.xE("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),l8(" -- with channel params: "+
g.Ng(a)),BFa(a),c.start(),k8()||CFa())},FFa=function(){var a=EFa();
H7()&&g.FH("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},EFa=function(){var a=j8().pd.$_gos();
var b=q8();b&&r8()&&(j6(a,b)||a.push(b));return CDa(a)},s8=function(){var a=GFa();
!a&&H7()&&fFa()&&(a={key:"cast-selector-receiver",name:fFa()});return a},GFa=function(){var a=EFa(),b=q8();
b||(b=o8());return g.Oa(a,function(a){return b&&f6(b,a.key)?!0:!1})},q8=function(){var a=k8();
if(!a)return null;var b=j8().De();return k6(b,a)},AFa=function(a){l8("remote.onCastSessionChange_: "+g6(a));
if(a){var b=q8();b&&b.id==a.id?K7(b.id,"YouTube TV"):(b&&t8(),u8(a,1))}else r8()&&t8()},t8=function(){I7()?F7().stopSession():D7("stopSession called before API ready.");
var a=r8();a&&(a.disconnect(1),v8(null))},w8=function(){var a=r8();
return!!a&&3!=a.getProxyState()},l8=function(a){c7("remote",a)},j8=function(){if(!x8){var a=g.y("yt.mdx.remote.screenService_");
x8=a?new g8(a):null}return x8},k8=function(){return g.y("yt.mdx.remote.currentScreenId_")},HFa=function(a){g.ya("yt.mdx.remote.currentScreenId_",a,void 0)},IFa=function(){return g.y("yt.mdx.remote.connectData_")},n8=function(a){g.ya("yt.mdx.remote.connectData_",a,void 0)},r8=function(){return g.y("yt.mdx.remote.connection_")},v8=function(a){var b=r8();
n8(null);a||HFa("");g.ya("yt.mdx.remote.connection_",a,void 0);i8&&((0,g.D)(i8,function(b){b(a)}),i8.length=0);
b&&!a?c6("yt-remote-connection-change",!1):!b&&a&&c6("yt-remote-connection-change",!0)},o8=function(){var a=g.HH();
if(!a)return null;var b=j8().De();return k6(b,a)},u8=function(a,b){q8()&&q8();
HFa(a.id);var c=new $7(h8,a,p8());c.connect(b,IFa());c.subscribe("beforeDisconnect",function(a){c6("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){r8()&&v8(null)});
v8(c)},CFa=function(){var a=o8();
a?(l8("Resume connection to: "+g6(a)),u8(a,0)):(p6(),gFa(),l8("Skipping connecting because no session screen found."))},zFa=function(){var a=p8();
if(g.ec(a)){a=n6();var b=g.FH("yt-remote-session-name")||"",c=g.FH("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.ya("yt.mdx.remote.channelParams_",a,void 0)}},p8=function(){return g.y("yt.mdx.remote.channelParams_")||{}},BFa=function(a){a?(g.EH("yt-remote-session-app",a.app),g.EH("yt-remote-session-name",a.name)):(g.GH("yt-remote-session-app"),g.GH("yt-remote-session-name"));
g.ya("yt.mdx.remote.channelParams_",a,void 0)},y8=function(a,b,c){g.K.call(this);
this.D=a;this.A=b;this.B=new g.fG(this);g.M(this,this.B);this.B.R(b,"onCaptionsTrackListChanged",this.fT);this.B.R(b,"captionschanged",this.NR);this.B.R(b,"captionssettingschanged",this.bG);this.B.R(b,"videoplayerreset",this.yq);this.B.R(b,"mdxautoplaycancel",this.VJ);this.V=this.B.R(b,"onVolumeChange",this.cE);this.H=!1;this.o=c;c.subscribe("proxyStateChange",this.sE,this);c.subscribe("remotePlayerChange",this.tn,this);c.subscribe("remoteQueueChange",this.yq,this);c.subscribe("autoplayUpNext",this.OD,
this);c.subscribe("previousNextChange",this.pE,this);c.subscribe("nowAutoplaying",this.hE,this);c.subscribe("autoplayDismissed",this.ND,this);this.suggestion=null;this.J=new g.aQ(64);this.C=new g.V(this.XF,500,this);g.M(this,this.C);this.F=new g.V(this.YF,1E3,this);g.M(this,this.F);this.L=new x6(this.fX,0,this);g.M(this,this.L);this.G={};this.M=new g.V(this.zG,1E3,this);g.M(this,this.M);this.K=new g.Bl(this.PP,1E3,this);g.M(this,this.K);this.O=g.A;this.bG();this.yq();this.tn()},z8=function(a,b){var c=
a.D,d=a.A.getVideoData().lengthSeconds;
c.J=b||0;c.player.U("progresssync",b,d)},JFa=function(a){z8(a,0);
a.C.stop();A8(a,new g.aQ(64))},C8=function(a,b){if(B8(a)&&!a.H){var c=null;
b&&(c={style:a.A.Tg()},g.nc(c,b));a.o.MF(a.A.getVideoData(1).videoId,c);a.G=U7(a.o).o}},D8=function(a,b){var c=a.A.pg();
if(c){var d=c.Ce();var e=c.listId.toString()}var f=a.A.getVideoData(1);c=a.o;var k=f.videoId,l=d;d=f.playerParams;var m=f.hk;f=rDa(f);var n=U7(c);l=l||0;var p={videoId:k,currentIndex:l};Q7(n,k,l);g.u(b)&&(O7(n,b),p.currentTime=b);g.u(e)&&(p.listId=e);null!=d&&(p.playerParams=d);null!=m&&(p.clickTrackingParams=m);null!=f&&(p.locationInfo=g.Ng(f));Y7(c,"setPlaylist",p);e||W7(c,n);A8(a,new g.aQ(1))},KFa=function(a,b){if(b){var c=a.A.jc("captions","tracklist",{A5:1});
c&&c.length?(a.A.dd("captions","track",b),a.H=!1):(a.A.Ak("captions"),a.H=!0)}else a.A.dd("captions","track",{})},B8=function(a){return U7(a.o).videoId==a.A.getVideoData(1).videoId},A8=function(a,b){a.F.stop();
var c=a.J;if(!g.gQ(c,b)){var d=g.X(b,2);d!=g.X(a.J,2)&&g.vU(a.A,d);a.J=b;LFa(a.D,c,b)}},E8=function(a){g.W.call(this,{I:"div",
N:"ytp-remote",P:[{I:"div",N:"ytp-remote-display-status",P:[{I:"div",N:"ytp-remote-display-status-icon",P:[g.Sra()]},{I:"div",N:"ytp-remote-display-status-text",da:"{{statustext}}"}]}]});this.B=new g.rV(this,250);g.M(this,this.B);this.C=a;this.R(a,"presentingplayerstatechange",this.D);MFa(this,g.rU(a))},MFa=function(a,b){if(3==a.C.Sa()){var c={RECEIVER_NAME:a.C.jc("remote","currentReceiver").name};
c=g.X(b,128)?g.jV("Error on $RECEIVER_NAME",c):b.tb()||g.X(b,4)?g.jV("Playing on $RECEIVER_NAME",c):g.jV("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.B.show()}else a.B.hide()},F8=function(a,b){g.UY.call(this,"Play on",0,a,b);
this.B=a;this.J={};this.R(a,"onMdxReceiversChange",this.L);this.R(a,"presentingplayerstatechange",this.L);this.L()},G8=function(a){g.UU.call(this,a);
this.A={key:i6(),name:"This computer"};this.C=null;this.D=[];this.K=this.o=null;this.H=[this.A];this.B=this.A;this.F=new g.aQ(64);this.J=0;this.G=-1;if(!g.zN(g.Z(this.player))){a=this.player;var b=g.rI(a);b&&(b=b.cn())&&(b=new F8(a,b),g.M(this,b));b=new E8(a);g.M(this,b);g.KU(a,b.element,4)}},LFa=function(a,b,c){a.F=c;
a.player.U("presentingplayerstatechange",new g.lQ(c,b))},H8=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)t8();
else{a.B=b;var c=a.player.getPlaylistId();var d=a.player.getVideoData(1);var e=d.videoId;if(c||e){var f=a.player.pg();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.Ia(l).videoId}else k=[e];f=a.player.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.hk,index:Math.max(a.player.wC(),0),currentTime:0==f?void 0:f};(d=rDa(d))&&(c.locationInfo=d);d=c}else d=null;l8("Connecting to: "+g.Ng(b));"cast-selector-receiver"==b.key?(n8(d||null),I7()?F7().setLaunchParams(d||
null):D7("setLaunchParams called before ready.")):!d&&w8()&&k8()==b.key?c6("yt-remote-connection-change",!0):(t8(),n8(d||null),d=j8().De(),(d=k6(d,b.key))&&u8(d,1))}},aEa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},H6={"'":"\\'"},NFa={},yDa={aZ:"atp",F3:"ska",W2:"que",g2:"mus",B3:"sus",n0:"dsp"};
d6.prototype.ph=function(){var a=new d6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.B=this.B;a.A=this.A;a.o=this.o};
var q6,m6="",u6=r6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",TDa=r6("loadCastFramework")||r6("loadCastApplicationFramework"),cFa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.C(x6,g.K);g.h=x6.prototype;g.h.QK=function(a){this.C=arguments;this.o=!1;this.Ha?this.B=(0,g.I)()+this.Hd:this.Ha=g.Ig(this.D,this.Hd)};
g.h.stop=function(){this.Ha&&(g.Jg(this.Ha),this.Ha=null);this.B=null;this.o=!1;this.C=[]};
g.h.pause=function(){++this.A};
g.h.resume=function(){this.A&&(--this.A,!this.A&&this.o&&(this.o=!1,this.F.apply(null,this.C)))};
g.h.X=function(){this.stop();x6.ga.X.call(this)};
g.h.RK=function(){this.B?(this.Ha=g.Ig(this.D,this.B-(0,g.I)()),this.B=null):(this.Ha=null,this.A?this.o=!0:(this.o=!1,this.F.apply(null,this.C)))};y6.prototype.stringify=function(a){return g.x.JSON.stringify(a,void 0)};
y6.prototype.parse=function(a){return g.x.JSON.parse(a,void 0)};g.h=z6.prototype;g.h.Mi=null;g.h.Of=!1;g.h.ql=null;g.h.Fx=null;g.h.Tk=null;g.h.Xj=null;g.h.Ah=null;g.h.ci=null;g.h.nj=null;g.h.Wc=null;g.h.Nn=0;g.h.Pf=null;g.h.zr=null;g.h.Bh=null;g.h.km=-1;g.h.uF=!0;g.h.xi=!1;g.h.Lt=0;g.h.Jq=null;var ZDa={},C6={};g.h=z6.prototype;g.h.setTimeout=function(a){this.C=a};
g.h.fW=function(a){a=a.target;var b=this.Jq;b&&3==g.Px(a)?b.gm():this.KG(a)};
g.h.KG=function(a){try{if(a==this.Wc)a:{var b=g.Px(this.Wc),c=this.Wc.A,d=this.Wc.getStatus();if(g.Qd&&!g.Bc(10)||g.Sd&&!g.Ac("420+")){if(4>b)break a}else if(3>b||3==b&&!g.xf&&!g.Tx(this.Wc))break a;this.xi||4!=b||7==c||(8==c||0>=d?this.o.Hf(3):this.o.Hf(2));J6(this);var e=this.Wc.getStatus();this.km=e;var f=g.Tx(this.Wc);(this.Of=200==e)?(4==b&&F6(this),this.D?($Da(this,b,f),g.xf&&this.Of&&3==b&&(this.Y.W(this.A,"tick",this.cW),this.A.start())):E6(this,f),this.Of&&!this.xi&&(4==b?this.o.wq(this):
(this.Of=!1,B6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Bh=3,D6(13)):(this.Bh=0,D6(14)),F6(this),G6(this))}}catch(k){this.Wc&&g.Tx(this.Wc)}finally{}};
g.h.cW=function(){var a=g.Px(this.Wc),b=g.Tx(this.Wc);this.Nn<b.length&&(J6(this),$Da(this,a,b),this.Of&&4!=a&&B6(this))};
g.h.oV=function(a){I6((0,g.B)(this.nV,this,a),0)};
g.h.nV=function(a){this.xi||(J6(this),E6(this,a),B6(this))};
g.h.BE=function(a){I6((0,g.B)(this.mV,this,a),0)};
g.h.mV=function(a){this.xi||(F6(this),this.Of=a,this.o.wq(this),this.o.Hf(4))};
g.h.cancel=function(){this.xi=!0;F6(this)};
g.h.EV=function(){this.ql=null;var a=(0,g.I)();0<=a-this.Fx?(2!=this.Xj&&this.o.Hf(3),F6(this),this.Bh=2,D6(18),G6(this)):cEa(this,this.Fx-a)};g.h=fEa.prototype;g.h.Jt=null;g.h.Je=null;g.h.Kq=!1;g.h.TA=null;g.h.bp=null;g.h.Fu=null;g.h.Kt=null;g.h.ff=null;g.h.Ng=-1;g.h.jm=null;g.h.wl=null;g.h.connect=function(a){this.Kt=a;a=L6(this.o,null,this.Kt);D6(3);this.TA=(0,g.I)();var b=this.o.H;null!=b?(this.jm=b[0],(this.wl=b[1])?(this.ff=1,gEa(this)):(this.ff=2,N6(this))):(b6(a,"MODE","init"),this.Je=new z6(this,void 0,void 0,void 0),this.Je.Mi=this.Jt,A6(this.Je,a,!1,null,!0),this.ff=0)};
g.h.WJ=function(a){if(a)this.ff=2,N6(this);else{D6(4);var b=this.o;b.Zf=b.oh.Ng;U6(b,9)}a&&this.Hf(2)};
g.h.Qs=function(a){return this.o.Qs(a)};
g.h.abort=function(){this.Je&&(this.Je.cancel(),this.Je=null);this.Ng=-1};
g.h.SA=function(){return!1};
g.h.tE=function(a,b){this.Ng=a.km;if(0==this.ff)if(b){try{var c=this.A.parse(b)}catch(d){c=this.o;c.Zf=this.Ng;U6(c,2);return}this.jm=c[0];this.wl=c[1]}else c=this.o,c.Zf=this.Ng,U6(c,2);else if(2==this.ff)if(this.Kq)D6(7),this.Fu=(0,g.I)();else if("11111"==b){if(D6(6),this.Kq=!0,this.bp=(0,g.I)(),c=this.bp-this.TA,!g.Qd||g.Bc(10)||500>c)this.Ng=200,this.Je.cancel(),D6(12),M6(this.o,this,!0)}else D6(8),this.bp=this.Fu=(0,g.I)(),this.Kq=!1};
g.h.wq=function(){this.Ng=this.Je.km;if(this.Je.Of)0==this.ff?this.wl?(this.ff=1,gEa(this)):(this.ff=2,N6(this)):2==this.ff&&((!g.Qd||g.Bc(10)?!this.Kq:200>this.Fu-this.bp)?(D6(11),M6(this.o,this,!1)):(D6(12),M6(this.o,this,!0)));else{0==this.ff?D6(9):2==this.ff&&D6(10);var a=this.o;a.Zf=this.Ng;U6(a,2)}};
g.h.Fn=function(){return this.o.Fn()};
g.h.isActive=function(){return this.o.isActive()};
g.h.Hf=function(a){this.o.Hf(a)};g.h=O6.prototype;g.h.Ml=null;g.h.ne=null;g.h.Bc=null;g.h.It=null;g.h.ep=null;g.h.pz=null;g.h.rp=null;g.h.kn=0;g.h.gR=0;g.h.Gd=null;g.h.uh=null;g.h.Bg=null;g.h.Bi=null;g.h.oh=null;g.h.xr=null;g.h.rk=-1;g.h.IB=-1;g.h.Zf=-1;g.h.Oj=0;g.h.Fj=0;g.h.zi=8;var V6=new g.Wf;g.C(iEa,g.vf);g.C(jEa,g.vf);g.C(kEa,g.vf);g.h=O6.prototype;g.h.connect=function(a,b,c,d,e){D6(0);this.It=b;this.Ml=c||{};d&&g.u(e)&&(this.Ml.OSID=d,this.Ml.OAID=e);this.F?(I6((0,g.B)(this.Hz,this,a),100),oEa(this)):this.Hz(a)};
g.h.Hz=function(a){this.oh=new fEa(this);this.oh.Jt=null;this.oh.A=this.D;this.oh.connect(a)};
g.h.SA=function(){return 0==this.o};
g.h.zE=function(a){this.uh=null;rEa(this,a)};
g.h.yE=function(){this.Bg=null;this.Bc=new z6(this,this.B,"rpc",this.G);this.Bc.Mi=null;this.Bc.Lt=0;var a=this.pz.clone();g.jn(a,"RID","rpc");g.jn(a,"SID",this.B);g.jn(a,"CI",this.xr?"0":"1");g.jn(a,"AID",this.rk);P6(this,a);if(!g.Qd||g.Bc(10))g.jn(a,"TYPE","xmlhttp"),A6(this.Bc,a,!0,this.rp,!1);else{g.jn(a,"TYPE","html");var b=this.Bc,c=!!this.rp;b.Xj=3;b.Ah=a6(a.clone());bEa(b,c)}};
g.h.tE=function(a,b){if(0!=this.o&&(this.Bc==a||this.ne==a))if(this.Zf=a.km,this.ne==a&&3==this.o)if(7<this.zi){try{var c=this.D.parse(b)}catch(f){c=null}if(g.Ba(c)&&3==c.length)if(0==c[0])a:{if(!this.Bg){if(this.Bc)if(this.Bc.Tk+3E3<this.ne.Tk)R6(this),this.Bc.cancel(),this.Bc=null;else break a;T6(this);D6(19)}}else this.IB=c[1],0<this.IB-this.rk&&37500>c[2]&&this.xr&&0==this.Fj&&!this.Bi&&(this.Bi=I6((0,g.B)(this.IR,this),6E3));else U6(this,11)}else b!=NFa.d_.o&&U6(this,11);else if(this.Bc==a&&
R6(this),!g.F(b)){c=this.D.parse(b);g.Ba(c);for(var d=0;d<c.length;d++){var e=c[d];this.rk=e[0];e=e[1];2==this.o?"c"==e[0]?(this.B=e[1],this.rp=e[2],e=e[3],null!=e?this.zi=e:this.zi=6,this.o=3,this.Gd&&this.Gd.Cz(),this.pz=L6(this,this.Fn()?this.rp:null,this.It),sEa(this)):"stop"==e[0]&&U6(this,7):3==this.o&&("stop"==e[0]?U6(this,7):"noop"!=e[0]&&this.Gd&&this.Gd.Bz(e),this.Fj=0)}}};
g.h.IR=function(){null!=this.Bi&&(this.Bi=null,this.Bc.cancel(),this.Bc=null,T6(this),D6(20))};
g.h.wq=function(a){if(this.Bc==a){R6(this);this.Bc=null;var b=2}else if(this.ne==a)this.ne=null,b=1;else return;this.Zf=a.km;if(0!=this.o)if(a.Of)1==b?(b=(0,g.I)()-a.Tk,V6.dispatchEvent(new jEa(V6,a.nj?a.nj.length:0,b,this.Oj)),Q6(this),this.C.length=0):sEa(this);else{var c=a.Bh,d;if(!(d=3==c||7==c||0==c&&0<this.Zf)){if(d=1==b)this.ne||this.uh||1==this.o||2<=this.Oj?d=!1:(this.uh=I6((0,g.B)(this.zE,this,a),tEa(this,this.Oj)),this.Oj++,d=!0);d=!(d||2==b&&T6(this))}if(d)switch(c){case 1:U6(this,5);
break;case 4:U6(this,10);break;case 3:U6(this,6);break;case 7:U6(this,12);break;default:U6(this,2)}}};
g.h.rK=function(a){if(!g.Ta(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.VW=function(a){a?D6(2):(D6(1),uEa(this,8))};
g.h.Qs=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.Jx;a.H=!1;return a};
g.h.isActive=function(){return!!this.Gd&&this.Gd.isActive(this)};
g.h.Hf=function(a){V6.dispatchEvent(new kEa(V6,a))};
g.h.Fn=function(){return!(!g.Qd||g.Bc(10))};
g.h=vEa.prototype;g.h.Cz=function(){};
g.h.Bz=function(){};
g.h.Az=function(){};
g.h.Ds=function(){};
g.h.AA=function(){return{}};
g.h.isActive=function(){return!0};g.C(W6,g.K);g.h=W6.prototype;g.h.fV=function(){this.Hd=Math.min(3E5,2*this.Hd);this.B();this.A&&this.start()};
g.h.start=function(){var a=this.Hd+15E3*Math.random();g.Iu(this.o,a);this.A=(0,g.I)()+a};
g.h.stop=function(){this.o.stop();this.A=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.Hd=5E3};g.C(X6,vEa);g.h=X6.prototype;g.h.subscribe=function(a,b,c){return this.B.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.B.unsubscribe(a,b,c)};
g.h.yk=function(a){return this.B.Ni(a)};
g.h.U=function(a,b){return this.B.U.apply(this.B,arguments)};
g.h.dispose=function(){this.K||(this.K=!0,g.tf(this.B),yEa(this),g.tf(this.A),this.A=null)};
g.h.la=function(){return this.K};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.J="";this.A.stop();this.D=a||null;this.C=b||0;a=this.L+"/test";b=this.L+"/bind";var d=new O6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.M),e=this.o;e&&(e.Gd=null);d.Gd=this;this.o=d;e?this.o.connect(a,b,this.F,e.B,e.rk):c?this.o.connect(a,b,this.F,c.sessionId,c.arrayId):this.o.connect(a,b,this.F)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.nc(c,b);this.A.isActive()||2==(this.o?this.o.o:0)?this.G.push(c):Y6(this)&&pEa(this.o,c)};
g.h.Cz=function(){this.A.reset();this.D=null;this.C=0;if(this.G.length){var a=this.G;this.G=[];for(var b=0,c=a.length;b<c;++b)pEa(this.o,a[b])}this.U("handlerOpened")};
g.h.Az=function(a){var b=2==a&&401==this.o.Zf;4==a||b||this.A.start();this.U("handlerError",a)};
g.h.Ds=function(a){if(!this.A.isActive())this.U("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.G.push(d)}};
g.h.AA=function(){var a={v:2};this.J&&(a.gsessionid=this.J);0!=this.C&&(a.ui=""+this.C);0!=this.H&&(a.ui=""+this.H);this.D&&g.nc(a,this.D);return a};
g.h.Bz=function(a){"S"==a[0]?this.J=a[1]:"gracefulReconnect"==a[0]?(this.A.start(),nEa(this.o)):this.U("handlerMessage",new wEa(a[0],a[1]))};
g.h.yX=function(){this.A.isActive();var a=this.o,b=0;a.Bc&&b++;a.ne&&b++;0!=b||this.connect(this.D,this.C)};Z6.prototype.C=function(a,b,c,d){b?a(d):a({text:c.responseText})};
Z6.prototype.B=function(a,b){a(Error("Request error: "+b.status))};
Z6.prototype.D=function(a){a(Error("request timed out"))};var GEa=(0,g.I)(),b7=null,e7=Array(50),d7=-1,f7=!1;g.C(g7,g.iG);g7.prototype.De=function(){return this.o};
g7.prototype.contains=function(a){return!!j6(this.o,a)};
g7.prototype.get=function(a){return a?k6(this.o,a):null};
g7.prototype.info=function(a){c7(this.G,a)};g.C(h7,g.iG);var OFa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=h7.prototype;g.h.start=function(){!this.o&&(0,window.isNaN)(this.Ha)&&this.QG()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);(0,window.isNaN)(this.Ha)||(g.CE(this.Ha),this.Ha=window.NaN)};
g.h.X=function(){this.stop();h7.ga.X.call(this)};
g.h.QG=function(){this.Ha=window.NaN;this.o=g.RE($6(this.F,"/pairing/get_screen"),{method:"POST",Tb:{pairing_code:this.D},timeout:5E3,onSuccess:(0,g.B)(this.AX,this),onError:(0,g.B)(this.zX,this),Md:(0,g.B)(this.BX,this)})};
g.h.AX=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.B;c.name=this.C;this.U("pairingComplete",new e6(c))};
g.h.zX=function(a){this.o=null;a.status&&404==a.status?this.A>=OFa.length?this.U("pairingFailed",Error("DIAL polling timed out")):(a=OFa[this.A],this.Ha=g.AE((0,g.B)(this.QG,this),a),this.A++):this.U("pairingFailed",Error("Server error "+a.status))};
g.h.BX=function(){this.o=null;this.U("pairingFailed",Error("Server not responding"))};g.C(j7,g7);g.h=j7.prototype;g.h.start=function(){i7(this)&&this.U("screenChange");!g.FH("yt-remote-lounge-token-expiration")&&KEa(this);g.CE(this.A);this.A=g.AE((0,g.B)(this.start,this),1E4)};
g.h.add=function(a,b){i7(this);HEa(this,a);k7(this,!1);this.U("screenChange");b(a);a.token||KEa(this)};
g.h.remove=function(a,b){var c=i7(this);JEa(this,a)&&(k7(this,!1),c=!0);b(a);c&&this.U("screenChange")};
g.h.tr=function(a,b,c,d){var e=i7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,k7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.U("screenChange")};
g.h.X=function(){g.CE(this.A);j7.ga.X.call(this)};
g.h.gL=function(a){i7(this);var b=this.o.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}k7(this,!b);b&&c7(this.G,"Missed "+b+" lounge tokens.")};
g.h.fL=function(a){c7(this.G,"Requesting lounge tokens failed: "+a)};g.C(m7,g.iG);g.h=m7.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.FH("yt-remote-fast-check-period")||"0",10);(this.C=(0,g.I)()-144E5<a?0:a)?o7(this):(this.C=(0,g.I)()+3E5,g.EH("yt-remote-fast-check-period",this.C),this.Dw())};
g.h.isEmpty=function(){return g.ec(this.o)};
g.h.update=function(){l7("Updating availability on schedule.");var a=this.F(),b=g.Pb(this.o,function(b,d){return b&&!!k6(a,d)},this);
n7(this,b)};
g.h.X=function(){g.CE(this.B);this.B=window.NaN;this.A&&(this.A.abort(),this.A=null);m7.ga.X.call(this)};
g.h.Dw=function(){g.CE(this.B);this.B=window.NaN;this.A&&this.A.abort();var a=NEa(this);if(g.Tb(a)){var b=$6(this.D,"/pairing/get_screen_availability");this.A=a7(this.D,b,{lounge_token:g.Zb(a).join(",")},(0,g.B)(this.OU,this,a),(0,g.B)(this.NU,this))}else n7(this,{}),o7(this)};
g.h.OU=function(a,b){this.A=null;var c=g.Zb(NEa(this));if(g.ob(c,g.Zb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;n7(this,d);o7(this)}else this.uc("Changing Screen set during request."),this.Dw()};
g.h.NU=function(a){this.uc("Screen availability failed: "+a);this.A=null;o7(this)};
g.h.uc=function(a){c7("OnlineScreenService",a)};g.C(p7,g7);g.h=p7.prototype;g.h.start=function(){this.B.start();this.A.start();this.o.length&&(this.U("screenChange"),this.A.isEmpty()||this.U("onlineScreenChange"))};
g.h.add=function(a,b,c){this.B.add(a,b,c)};
g.h.remove=function(a,b,c){this.B.remove(a,b,c);this.A.update()};
g.h.tr=function(a,b,c,d){this.B.contains(a)?this.B.tr(a,b,c,d):(a="Updating name of unknown screen: "+a.name,c7(this.G,a),d(Error(a)))};
g.h.De=function(a){return a?this.o:g.ab(this.o,(0,g.de)(this.C,function(a){return!this.contains(a)},this))};
g.h.SG=function(){return(0,g.de)(this.De(!0),function(a){return!!this.A.o[a.id]},this)};
g.h.TG=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new h7(this.F,a,b,c);f.subscribe("pairingComplete",(0,g.B)(function(a){g.tf(f);d(q7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.tf(f);e(a)});
f.start();return(0,g.B)(f.stop,f)};
g.h.DX=function(a,b,c,d){g.RE($6(this.F,"/pairing/get_screen"),{method:"POST",Tb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.B)(function(a,d){var e=new e6(d.screen||{});if(!e.name||REa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);REa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(q7(this,e))},this),
onError:(0,g.B)(function(a){d(Error("pairing request failed: "+a.status))},this),
Md:(0,g.B)(function(){d(Error("pairing request timed out."))},this)})};
g.h.X=function(){g.tf(this.B);g.tf(this.A);p7.ga.X.call(this)};
g.h.tL=function(){SEa(this);this.U("screenChange");this.A.update()};
p7.prototype.dispose=p7.prototype.dispose;g.C(s7,g.iG);g.h=s7.prototype;g.h.xq=function(a){this.B=a;this.U("sessionScreen",this.B)};
g.h.Ie=function(a){this.la()||(a&&t7(this,""+a),this.B=null,this.U("sessionScreen",null))};
g.h.info=function(a){c7(this.M,a)};
g.h.VG=function(){return null};
g.h.Ow=function(a){var b=this.A;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.B)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.B)(function(){t7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.X=function(){this.Ow("");s7.ga.X.call(this)};g.C(u7,s7);g.h=u7.prototype;g.h.Nw=function(a){if(this.o){if(this.o==a)return;t7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.F);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D)}this.o=a;this.o.addUpdateListener(this.F);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.D);UEa(this)};
g.h.tk=function(a){this.info("launchWithParams no-op for Cast: "+g.Ng(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.B)(function(){this.Ie()},this),(0,g.B)(function(){this.Ie(Error("Failed to stop receiver app."))},this)):this.Ie(Error("Stopping cast device witout session."))};
g.h.Ow=g.A;g.h.X=function(){this.info("disposeInternal");g.CE(this.C);this.C=0;this.o&&(this.o.removeUpdateListener(this.F),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D));this.o=null;u7.ga.X.call(this)};
g.h.QV=function(a,b){if(!this.la())if(b){var c=g.Dx(b);if(g.Ea(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Ng(c));switch(d){case "mdxSessionStatus":TEa(this,c.screenId);break;default:t7(this,"Unknown youtube message: "+d)}}else t7(this,"Unable to parse message.")}else t7(this,"No data in message.")};
g.h.IA=function(a,b,c,d){QEa(this.J,this.A.label,a,this.A.friendlyName,(0,g.B)(function(e){e?b(e):0<=d?(t7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.AE((0,g.B)(this.IA,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.VG=function(){return this.o};
g.h.EX=function(a){this.la()||a||(t7(this,"Cast session died."),this.Ie())};g.C(v7,s7);g.h=v7.prototype;g.h.Nw=function(a){this.C=a;this.C.addUpdateListener(this.L)};
g.h.tk=function(a){this.D=a;this.G()};
g.h.stop=function(){this.o();this.o=g.A;g.CE(this.F);this.C?this.C.stop((0,g.B)(this.Ie,this,null),(0,g.B)(this.Ie,this,"Failed to stop DIAL device.")):this.Ie()};
g.h.X=function(){this.o();this.o=g.A;g.CE(this.F);this.C&&this.C.removeUpdateListener(this.L);this.C=null;v7.ga.X.call(this)};
g.h.HX=function(a){this.la()||a||(t7(this,"DIAL session died."),this.o(),this.o=g.A,this.Ie())};
g.h.nu=function(a){this.K=i6();if(this.D){var b=new window.chrome.cast.DialLaunchResponse(!0,WEa(this));a(b);VEa(this)}else this.G=(0,g.B)(function(){g.CE(this.F);this.G=g.A;this.F=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,WEa(this));a(b);VEa(this)},this),this.F=g.AE((0,g.B)(function(){this.G()},this),100)};
g.h.FM=function(a,b,c){QEa(this.J,this.H.receiver.label,a,this.A.friendlyName,(0,g.B)(function(a){a&&a.token?(this.xq(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.nu(b,c)},this),(0,g.B)(function(a){t7(this,"Failed to get DIAL screen: "+a);
this.nu(b,c)},this))};g.C(w7,s7);w7.prototype.stop=function(){this.Ie()};
w7.prototype.Nw=g.A;w7.prototype.tk=function(){g.CE(this.o);this.o=window.NaN;var a=k6(this.J.De(),this.A.label);a?this.xq(a):this.Ie(Error("No such screen"))};
w7.prototype.X=function(){g.CE(this.o);this.o=window.NaN;w7.ga.X.call(this)};g.C(x7,g.iG);g.h=x7.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.G);this.H||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.B)(this.vE,this),(0,g.B)(this.xU,this),d,e);c.customDialLaunchCallback=(0,g.B)(this.qS,this);window.chrome.cast.initialize(c,
(0,g.B)(function(){this.la()||(window.chrome.cast.addReceiverActionListener(this.C),DEa(),this.A.subscribe("onlineScreenChange",(0,g.B)(this.UG,this)),this.B=YEa(this),window.chrome.cast.setCustomReceivers(this.B,g.A,(0,g.B)(function(a){this.uc("Failed to set initial custom receivers: "+g.Ng(a))},this)),this.U("yt-remote-cast2-availability-change",z7(this)),b(!0))},this),(0,g.B)(function(a){this.uc("Failed to initialize API: "+g.Ng(a));
b(!1)},this))};
g.h.EW=function(a,b){y7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.B;if(!a||c&&c.id!=a)y7("Unsetting old screen status: "+this.o.A.friendlyName),A7(this,null)}if(a&&b){if(!this.o){c=k6(this.A.De(),a);if(!c){y7("setConnectedScreenStatus: Unknown screen.");return}var d=XEa(this,c);d||(y7("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.B.push(d),
window.chrome.cast.setCustomReceivers(this.B,g.A,(0,g.B)(function(a){this.uc("Failed to set initial custom receivers: "+g.Ng(a))},this)));
y7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);A7(this,new w7(this.A,d),!0)}this.o.Ow(b)}else y7("setConnectedScreenStatus: no screen.")};
g.h.FW=function(a){this.la()?this.uc("Setting connection data on disposed cast v2"):this.o?this.o.tk(a):this.uc("Setting connection data without a session")};
g.h.GX=function(){this.la()?this.uc("Stopping session on disposed cast v2"):this.o?(this.o.stop(),A7(this,null)):y7("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.B)(this.vE,this),(0,g.B)(this.SU,this))};
g.h.X=function(){this.A.unsubscribe("onlineScreenChange",(0,g.B)(this.UG,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.C);g.Ya(g.y("yt.mdx.remote.debug.handlers_")||[],AEa);g.tf(this.o);x7.ga.X.call(this)};
g.h.uc=function(a){c7("Controller",a)};
g.h.wE=function(a,b){this.o==a&&(b||A7(this,null),this.U("yt-remote-cast2-session-change",b))};
g.h.tU=function(a,b){if(!this.la())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),y7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.A.label!=a.label)y7("onReceiverAction_: Stopping active receiver: "+this.o.A.friendlyName),this.o.stop();else{y7("onReceiverAction_: Casting to active receiver.");this.o.B&&this.U("yt-remote-cast2-session-change",this.o.B);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:A7(this,
new w7(this.A,a));break;case window.chrome.cast.ReceiverType.DIAL:A7(this,new v7(this.A,a,this.F));break;case window.chrome.cast.ReceiverType.CAST:A7(this,new u7(this.A,a));break;default:this.uc("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.o&&this.o.A.label==a.label?this.o.stop():this.uc("Stopping receiver w/o session: "+a.friendlyName)}else this.uc("onReceiverAction_ called without receiver.")};
g.h.qS=function(a){if(this.la())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.uc("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.A:null;if(!c||c.label!=b.label)return this.uc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.o.B)return y7("Reselecting dial screen."),
this.U("yt-remote-cast2-session-change",this.o.B),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.uc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);A7(this,new v7(this.A,b,this.F))}b=this.o;b.H=a;return b.H.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.B)(b.FM,b,(b.H.extraData||{}).screenId||null)):new window.Promise((0,g.B)(b.nu,b))};
g.h.vE=function(a){if(!this.la()){y7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)y7("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),A7(this,new u7(this.A,b),!0);else{this.uc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.A,d=k6(this.A.De(),c.label);
d&&f6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(y7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.tf(this.o),this.o=new u7(this.A,b),this.o.subscribe("sessionScreen",(0,g.B)(this.wE,this,this.o)),this.o.tk(null));this.o.Nw(a)}}};
g.h.FX=function(){return this.o?this.o.VG():null};
g.h.SU=function(a){this.la()||(this.uc("Failed to estabilish a session: "+g.Ng(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&A7(this,null))};
g.h.xU=function(a){y7("Receiver availability updated: "+a);if(!this.la()){var b=z7(this);this.D=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;z7(this)!=b&&this.U("yt-remote-cast2-availability-change",z7(this))}};
g.h.UG=function(){this.la()||(this.B=YEa(this),y7("Updating custom receivers: "+g.Ng(this.B)),window.chrome.cast.setCustomReceivers(this.B,g.A,(0,g.B)(function(){this.uc("Failed to set custom receivers.")},this)),this.U("yt-remote-cast2-availability-change",z7(this)))};
x7.prototype.setLaunchParams=x7.prototype.FW;x7.prototype.setConnectedScreenStatus=x7.prototype.EW;x7.prototype.stopSession=x7.prototype.GX;x7.prototype.getCastSession=x7.prototype.FX;x7.prototype.requestSession=x7.prototype.requestSession;x7.prototype.init=x7.prototype.init;x7.prototype.dispose=x7.prototype.dispose;var G7=[];g.h=L7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";M7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.eg=a.hasPrevious,this.hasNext=a.hasNext,this.G=a.playerTime,this.F=a.playerTimeAt,this.C=a.seekableStart,this.A=a.seekableEnd,this.H=a.duration,this.J=a.loadedTime,this.B=a.liveIngestionTime,this.D=!(0,window.isNaN)(this.B))};
g.h.tb=function(){return 1==this.playerState};
g.h.isAdPlaying=function(){return 1081==this.playerState};
g.h.getDuration=function(){return this.D?this.H+N7(this):this.H};
g.h.clone=function(){return new L7(R7(this))};g.C(T7,g.iG);g.h=T7.prototype;g.h.play=function(){1==this.o?(this.A?this.A.play(null,g.A,Z7(this,"play")):Y7(this,"play"),X7(this,1,P7(U7(this))),this.U("remotePlayerChange")):V7(this,this.play)};
g.h.pause=function(){1==this.o?(this.A?this.A.pause(null,g.A,Z7(this,"pause")):Y7(this,"pause"),X7(this,2,P7(U7(this))),this.U("remotePlayerChange")):V7(this,this.pause)};
g.h.PG=function(a){if(1==this.o){if(this.A){var b=U7(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.tb()||3==b.playerState?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.A.seek(c,g.A,Z7(this,"seekTo",{newTime:a}))}else Y7(this,"seekTo",{newTime:a});X7(this,3,a);this.U("remotePlayerChange")}else V7(this,g.Ha(this.PG,a))};
g.h.stop=function(){if(1==this.o){this.A?this.A.stop(null,g.A,Z7(this,"stopVideo")):Y7(this,"stopVideo");var a=U7(this);a.index=-1;a.videoId="";M7(a);W7(this,a);this.U("remotePlayerChange")}else V7(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=U7(this);if(this.B){if(c.volume!=a){var d=Math.round(a)/100;this.B.setReceiverVolumeLevel(d,(0,g.B)(function(){c7("CP","set receiver volume: "+d)},this),(0,g.B)(function(){this.uc("failed to set receiver volume.")},this))}c.muted!=b&&this.B.setReceiverMuted(b,(0,g.B)(function(){c7("CP","set receiver muted: "+b)},this),(0,g.B)(function(){this.uc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);Y7(this,"setVolume",e)}c.muted=b;c.volume=a;W7(this,c)}else V7(this,g.Ha(this.setVolume,a,b))};
g.h.MF=function(a,b){if(1==this.o){var c=U7(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Ng(b.style),g.nc(d,c.o));Y7(this,"setSubtitlesTrack",d);W7(this,c)}else V7(this,g.Ha(this.MF,a,b))};
g.h.Mx=function(a,b){if(1==this.o){Y7(this,"setAudioTrack",{videoId:a,audioTrackId:b.Pb.id});var c=U7(this);c.audioTrackId=b.Pb.id;W7(this,c)}else V7(this,g.Ha(this.Mx,a,b))};
g.h.OG=function(a,b){if(1==this.o){if(a&&b){var c=U7(this);Q7(c,a,b);W7(this,c)}Y7(this,"previous")}else V7(this,g.Ha(this.OG,a,b))};
g.h.NG=function(a,b){if(1==this.o){if(a&&b){var c=U7(this);Q7(c,a,b);W7(this,c)}Y7(this,"next")}else V7(this,g.Ha(this.NG,a,b))};
g.h.bA=function(){1==this.o?Y7(this,"dismissAutoplay"):V7(this,this.bA)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.U("proxyStateChange",a,this.o)}T7.ga.dispose.call(this)};
g.h.X=function(){kFa(this);this.C=null;this.D.clear();S7(this,null);T7.ga.X.call(this)};
g.h.Nx=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.U("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)g.XC(this.D).apply(this);else 3==a&&this.dispose()}};
g.h.oU=function(a,b){this.U(a,b)};
g.h.PR=function(a){if(!a)this.nn(null),S7(this,null);else if(this.B.receiver.volume){a=this.B.receiver.volume;var b=U7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)c7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,W7(this,b)}};
g.h.nn=function(a){c7("CP","Cast media: "+!!a);this.A&&this.A.removeUpdateListener(this.H);if(this.A=a)this.A.addUpdateListener(this.H),lFa(this),this.U("remotePlayerChange")};
g.h.OR=function(a){a?(lFa(this),this.U("remotePlayerChange")):this.nn(null)};
g.h.bS=function(){var a=hFa();a&&S7(this,a)};
g.h.uc=function(a){c7("CP",a)};g.C($7,g.iG);g.h=$7.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.u(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.u(k)&&(l.currentIndex=k);c&&(this.qb.listId=c);this.qb.videoId=d;this.qb.index=k||0;this.qb.state=3;O7(this.qb,m);this.C="UNSUPPORTED";a8("Connecting with setPlaylist and params: "+g.Ng(l));this.o.connect({method:"setPlaylist",
params:g.Ng(l)},a,GDa())}else a8("Connecting without params"),this.o.connect({},a,GDa());nFa(this)};
g.h.dispose=function(){this.la()||(this.U("beforeDispose"),b8(this,3));$7.ga.dispose.call(this)};
g.h.X=function(){c8(this);e8(this);d8(this);g.CE(this.J);this.J=window.NaN;g.CE(this.K);this.K=window.NaN;this.B=null;g.TF(this.V);this.V.length=0;this.o.dispose();$7.ga.X.call(this);this.C=this.G=this.A=this.qb=this.o=null};
g.h.VK=function(){this.F(2)};
g.h.TR=function(){a8("Channel opened");this.O&&(this.O=!1,d8(this),this.M=g.AE((0,g.B)(function(){a8("Timing out waiting for a screen.");this.F(1)},this),15E3));
KDa(xEa(this.o),this.ba)};
g.h.QR=function(){a8("Channel closed");(0,window.isNaN)(this.D)?p6(!0):p6();this.dispose()};
g.h.RR=function(a){p6();(0,window.isNaN)(this.H())?(a8("Channel error: "+a+" without reconnection"),this.dispose()):(this.O=!0,a8("Channel error: "+a+" with reconnection in "+this.H()+" ms"),b8(this,2))};
g.h.SR=function(a){a.params?a8("Received: action="+a.action+", params="+g.Ng(a.params)):a8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.Dx(a.params.devices);this.A=(0,g.J)(a,function(a){return new d6(a)});
a=!!g.Oa(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
qFa(this,a);break;case "loungeScreenDisconnected":g.Za(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
qFa(this,!1);break;case "remoteConnected":var b=new d6(g.Dx(a.params.device));g.Oa(this.A,function(a){return b?a.id==b.id:!1})||g.Wa(this.A,b);
break;case "remoteDisconnected":b=new d6(g.Dx(a.params.device));g.Za(this.A,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":sFa(this,a);break;case "nowPlaying":uFa(this,a);break;case "onStateChange":tFa(this,a);break;case "onAdStateChange":vFa(this,a);break;case "onVolumeChanged":wFa(this,a);break;case "onSubtitlesTrackChanged":rFa(this,a);break;case "nowAutoplaying":xFa(this,a);break;case "autoplayDismissed":this.U("autoplayDismissed");break;case "autoplayUpNext":this.G=a.params.videoId||null;this.U("autoplayUpNext",this.G);break;case "onAutoplayModeChanged":this.C=
a.params.autoplayMode;this.U("autoplayModeChange",this.C);"DISABLED"==this.C&&this.U("autoplayDismissed");break;case "onHasPreviousNextChanged":yFa(this,a);break;case "requestAssistedSignIn":this.U("assistedSignInRequested",a.params.authCode);break;default:a8("Unrecognized action: "+a.action)}};
g.h.nW=function(){if(this.B){var a=this.B;this.B=null;this.qb.videoId!=a&&f8(this,"getNowPlaying")}};
$7.prototype.subscribe=$7.prototype.subscribe;$7.prototype.unsubscribeByKey=$7.prototype.yk;$7.prototype.ha=function(){var a=3;this.la()||(a=0,(0,window.isNaN)(this.H())?Y6(this.o)&&(0,window.isNaN)(this.D)&&(a=1):a=2);return a};
$7.prototype.getProxyState=$7.prototype.ha;$7.prototype.F=function(a){a8("Disconnecting with "+a);c8(this);this.U("beforeDisconnect",a);1==a&&p6();yEa(this.o,a);this.dispose()};
$7.prototype.disconnect=$7.prototype.F;$7.prototype.fa=function(){var a=this.qb;this.B&&(a=this.qb.clone(),Q7(a,this.B,a.index));return R7(a)};
$7.prototype.getPlayerContextData=$7.prototype.fa;
$7.prototype.na=function(a){var b=new L7(a);b.videoId&&b.videoId!=this.qb.videoId&&(this.B=b.videoId,g.CE(this.J),this.J=g.AE((0,g.B)(this.nW,this),5E3));var c=[];this.qb.listId==b.listId&&this.qb.videoId==b.videoId&&this.qb.index==b.index||c.push("remoteQueueChange");this.qb.playerState==b.playerState&&this.qb.volume==b.volume&&this.qb.muted==b.muted&&P7(this.qb)==P7(b)&&g.Ng(this.qb.o)==g.Ng(b.o)||c.push("remotePlayerChange");this.qb.reset(a);(0,g.D)(c,function(a){this.U(a)},this)};
$7.prototype.setPlayerContextData=$7.prototype.na;$7.prototype.Z=function(){var a=this.o.F.id,b=g.Oa(this.A,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
$7.prototype.getOtherConnectedRemoteId=$7.prototype.Z;$7.prototype.H=function(){var a=this.o;return a.A.isActive()?a.A.A-(0,g.I)():window.NaN};
$7.prototype.getReconnectTimeout=$7.prototype.H;$7.prototype.aa=function(){return this.C||"UNSUPPORTED"};
$7.prototype.getAutoplayMode=$7.prototype.aa;$7.prototype.ca=function(){return this.G||""};
$7.prototype.getAutoplayVideoId=$7.prototype.ca;$7.prototype.xa=function(){if(!(0,window.isNaN)(this.H())){var a=this.o.A;g.Ju(a.o);a.start()}};
$7.prototype.reconnect=$7.prototype.xa;$7.prototype.ka=function(a,b){f8(this,a,b);pFa(this)};
$7.prototype.sendMessage=$7.prototype.ka;g.C(g8,g7);g.h=g8.prototype;g.h.De=function(a){return this.pd.$_gs(a)};
g.h.contains=function(a){return!!this.pd.$_c(a)};
g.h.get=function(a){return this.pd.$_g(a)};
g.h.start=function(){this.pd.$_st()};
g.h.add=function(a,b,c){this.pd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.pd.$_r(a,b,c)};
g.h.tr=function(a,b,c,d){this.pd.$_un(a,b,c,d)};
g.h.X=function(){for(var a=0,b=this.A.length;a<b;++a)this.pd.$_ubk(this.A[a]);this.A.length=0;this.pd=null;g8.ga.X.call(this)};
g.h.CX=function(){this.U("screenChange")};
g.h.KT=function(){this.U("onlineScreenChange")};
p7.prototype.$_st=p7.prototype.start;p7.prototype.$_gspc=p7.prototype.DX;p7.prototype.$_gsppc=p7.prototype.TG;p7.prototype.$_c=p7.prototype.contains;p7.prototype.$_g=p7.prototype.get;p7.prototype.$_a=p7.prototype.add;p7.prototype.$_un=p7.prototype.tr;p7.prototype.$_r=p7.prototype.remove;p7.prototype.$_gs=p7.prototype.De;p7.prototype.$_gos=p7.prototype.SG;p7.prototype.$_s=p7.prototype.subscribe;p7.prototype.$_ubk=p7.prototype.yk;var h8=null,i8=null,x8=null,m8=[];g.r(y8,g.K);g.h=y8.prototype;
g.h.X=function(){g.K.prototype.X.call(this);this.C.stop();this.F.stop();this.L.stop();this.O();this.o.unsubscribe("proxyStateChange",this.sE,this);this.o.unsubscribe("remotePlayerChange",this.tn,this);this.o.unsubscribe("remoteQueueChange",this.yq,this);this.o.unsubscribe("autoplayUpNext",this.OD,this);this.o.unsubscribe("previousNextChange",this.pE,this);this.o.unsubscribe("nowAutoplaying",this.hE,this);this.o.unsubscribe("autoplayDismissed",this.ND,this);this.o=this.D=null};
g.h.QC=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.o.o)if(B8(this)){if(!U7(this.o).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":U7(this.o).tb()?this.o.pause():this.o.play();break;case "control_play":this.o.play();break;case "control_pause":this.o.pause();break;case "control_seek":this.K.gm(c[0],c[1]);break;case "control_subtitles_set_track":C8(this,c[0]);break;case "control_set_audio_track":c=c[0],B8(this)&&this.o.Mx(this.A.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.A.getCurrentTime();D8(this,0==c?void 0:c);break;case "control_seek":D8(this,c[0]);break;case "control_subtitles_set_track":C8(this,c[0]);break;case "control_set_audio_track":c=c[0],B8(this)&&this.o.Mx(this.A.getVideoData(1).videoId,c)}};
g.h.NR=function(a){this.L.QK(a)};
g.h.fX=function(a){this.QC("control_subtitles_set_track",g.ec(a)?null:a)};
g.h.bG=function(){var a=this.A.jc("captions","track");g.ec(a)||C8(this,a)};
g.h.cE=function(a){if(B8(this)){this.o.unsubscribe("remotePlayerChange",this.tn,this);var b=Math.round(a.volume);a=!!a.muted;var c=U7(this.o);if(b!=c.volume||a!=c.muted)this.o.setVolume(b,a),this.M.start();this.o.subscribe("remotePlayerChange",this.tn,this)}};
g.h.fT=function(){g.ec(this.G)||KFa(this,this.G);this.H=!1};
g.h.sE=function(a,b){this.F.stop();2==b&&this.YF()};
g.h.tn=function(){if(B8(this)){this.C.stop();var a=U7(this.o);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.D.G=1;break;case 1082:case 1083:this.D.G=0;break;default:this.D.G=-1}switch(a.playerState){case 1081:case 1:A8(this,new g.aQ(8));this.XF();break;case 1085:case 3:A8(this,new g.aQ(9));break;case 1083:case 0:A8(this,new g.aQ(2));this.K.stop();z8(this,this.A.getVideoData().lengthSeconds);break;case 1084:A8(this,new g.aQ(4));break;case 2:A8(this,new g.aQ(4));z8(this,P7(a));
break;case -1:A8(this,new g.aQ(64));break;case -1E3:A8(this,new g.aQ(128,{errorCode:"mdx.remoteerror",message:"This video is not available for remote playback."}))}a=U7(this.o).o;var b=this.G;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.G=a,KFa(this,a));a=U7(this.o);-1==a.volume||Math.round(this.A.getVolume())==a.volume&&this.A.isMuted()==a.muted||this.M.isActive()||this.zG()}else JFa(this)};
g.h.pE=function(){this.A.U("mdxpreviousnextchange")};
g.h.yq=function(){B8(this)||JFa(this)};
g.h.VJ=function(){this.o.bA()};
g.h.OD=function(a){a&&(a=g.RE("/watch_queue_ajax",{method:"GET",hd:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.B)(this.qV,this)}))&&(this.O=(0,g.B)(a.abort,a))};
g.h.qV=function(a,b){var c=new g.qP(g.Z(this.A),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.A.U("mdxautoplayupnext",c)};
g.h.hE=function(a){(0,window.isNaN)(a)||this.A.U("mdxnowautoplaying",a)};
g.h.ND=function(){this.A.U("mdxautoplaycanceled")};
g.h.PP=function(a,b){-1==U7(this.o).playerState?D8(this,a):b&&this.o.PG(a)};
g.h.zG=function(){if(B8(this)){var a=U7(this.o);this.B.La(this.V);a.muted?this.A.mute():this.A.qg();this.A.setVolume(a.volume);this.V=this.B.R(this.A,"onVolumeChange",this.cE)}};
g.h.XF=function(){this.C.stop();if(!this.o.la()){var a=U7(this.o);a.tb()&&A8(this,new g.aQ(8));z8(this,P7(a));this.C.start()}};
g.h.YF=function(){this.F.stop();this.C.stop();var a=this.o.C.getReconnectTimeout();2==this.o.o&&!(0,window.isNaN)(a)&&this.F.start()};g.r(E8,g.W);E8.prototype.D=function(a){MFa(this,a.state)};g.r(F8,g.UY);F8.prototype.L=function(){var a=this.B.jc("remote","receivers");a&&1<a.length&&!this.B.jc("remote","quickCast")?(this.J=g.qb(a,this.F,this),g.VY(this,(0,g.J)(a,this.F)),a=this.B.jc("remote","currentReceiver"),this.Gf(this.F(a)),this.enable(!0)):this.enable(!1)};
F8.prototype.F=function(a){return a.key};
F8.prototype.Ff=function(a){return"cast-selector-receiver"==a?"Cast...":this.J[a].name};
F8.prototype.Kd=function(a){g.UY.prototype.Kd.call(this,a);this.B.dd("remote","currentReceiver",this.J[a]);this.D.Rb()};g.r(G8,g.UU);g.h=G8.prototype;g.h.create=function(){DFa(g.rN(g.Z(this.player)));this.D.push(g.vG("yt-remote-before-disconnect",this.JR,this));this.D.push(g.vG("yt-remote-connection-change",this.yU,this));this.D.push(g.vG("yt-remote-receiver-availability-change",this.qE,this));this.D.push(g.vG("yt-remote-auto-connect",this.wU,this));this.D.push(g.vG("yt-remote-receiver-resumed",this.vU,this));this.qE()};
g.h.load=function(){this.player.dv();g.UU.prototype.load.call(this);this.C=new y8(this,this.player,this.o);var a=(a=IFa())?a.currentTime:0;var b=w8()?new T7(r8(),void 0):null;0==a&&b&&(a=P7(U7(b)));0!=a&&(this.J=a||0,this.player.U("progresssync",a,void 0));LFa(this,this.F,this.F);g.n0(this.player.app,6)};
g.h.unload=function(){this.player.U("mdxautoplaycanceled");this.B=this.A;g.uf(this.C,this.o);this.o=this.C=null;g.UU.prototype.unload.call(this);g.n0(this.player.app,5)};
g.h.X=function(){g.wG(this.D);g.UU.prototype.X.call(this)};
g.h.an=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.C.QC.apply(this.C,[a].concat(g.ea(c)))};
g.h.LK=function(){return this.loaded?this.C.suggestion:null};
g.h.eg=function(){return this.o?U7(this.o).eg:!1};
g.h.hasNext=function(){return this.o?U7(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.J};
g.h.AP=function(){var a=U7(this.o),b=this.player.getVideoData();return{allowSeeking:g.Z(this.player).experiments.o("web_player_mdx_allow_seeking_change_killswitch")?this.player.Nc():!a.isAdPlaying()&&this.player.Nc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.D?a.B+N7(a):a.B,isPeggedToLive:1>=(a.D?a.A+N7(a):a.A)-this.getCurrentTime(),loaded:a.J,seekableEnd:a.D?a.A+N7(a):a.A,seekableStart:0<a.C?a.C+N7(a):a.C}};
g.h.BP=function(){this.o&&this.o.NG()};
g.h.CP=function(){this.o&&this.o.OG()};
g.h.JR=function(a){1==a&&(this.K=this.o?U7(this.o):null)};
g.h.yU=function(){var a=w8()?new T7(r8(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.K=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.tf(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.K)&&a.videoId==this.player.getVideoData().videoId&&this.player.uC(a.videoId,P7(a)));this.player.U("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.qE=function(){this.H=[this.A].concat(FFa());var a=s8()||this.A;H8(this,a);this.player.za("onMdxReceiversChange")};
g.h.wU=function(){var a=s8();H8(this,a)};
g.h.vU=function(){this.B=s8()};
g.h.zP=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.H;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?J7():H8(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.H.length&&"cast-selector-receiver"==this.H[1].key?(b&&J7(),!0):!1}};
g.h.DP=function(){Y7(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.zc=function(){return!1};g.SX.remote=G8;})(_yt_player);
